{% set version = '0.0.4' %}

package:
  name: cnapy
  version: {{ version }}

source:
  git_url: https://github.com/ARB-Lab/CNApy.git
  git_rev: v{{ version }}

requirements:
  build:
    - setuptools
    - pip
    - python=3.7
  run:
    - matplotlib-base
    - oct2py=5.2
    - openjdk=8
    - pip
    - pyside2
    - python=3.7
    - qtpy=1.9
    - appdirs
    - cobra=0.21
    - qtconsole=5.0
    # - cameo==0.13
build:
  number: 1  # NOTE: increment for new build/set to zero for new version
  entry_points:
    - cnapy = cnapy.__main__:main_cnapy
    - project-downloader = cnapy.project-downloader:main
test:
  imports:
    - cnapy

about:
  home:  https://github.com/ARB-Lab/CNApy
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: A CellNetAnalyzer GUI in Python
  doc_url: https://github.com/ARB-Lab/CNApy
  dev_url: https://github.com/ARB-Lab/CNApy